CVP_CONFIGLETS:
  OSPF-Underlay-Leafs: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-Leafs.cfg')}}"
  OSPF-Underlay-Spines: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-Spines.cfg')}}"
  OSPF-Underlay-borderleaf1-DC1: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-borderleaf1-DC1.cfg')}}"
  OSPF-Underlay-borderleaf2-DC1: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-borderleaf2-DC1.cfg')}}"
  OSPF-Underlay-leaf1-DC1: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf1-DC1.cfg')}}"
  OSPF-Underlay-leaf2-DC1: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf2-DC1.cfg')}}"
  OSPF-Underlay-leaf3-DC1: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf3-DC1.cfg')}}"
  OSPF-Underlay-leaf4-DC1: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf4-DC1.cfg')}}"
  OSPF-Underlay-borderleaf1-DC2: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-borderleaf1-DC2.cfg')}}"
  OSPF-Underlay-borderleaf2-DC2: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-borderleaf2-DC2.cfg')}}"
  OSPF-Underlay-leaf1-DC2: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf1-DC2.cfg')}}"
  OSPF-Underlay-leaf2-DC2: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf2-DC2.cfg')}}"
  OSPF-Underlay-leaf3-DC2: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf3-DC2.cfg')}}"
  OSPF-Underlay-leaf4-DC2: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-leaf4-DC2.cfg')}}"
  OSPF-Underlay-DCI: "{{lookup('file','{{path}}/configlets/OSPF-Underlay-DCI.cfg')}}"