---
- name: Assign configlets to devices (via group_vars/CVP.yml)
  hosts: CloudVision
  connection: local
  gather_facts: no

  vars: 
    path: "{{lookup('env','PWD')}}"
  vars_files: 
     - /home/coder/project/labfiles/ATD-Lab-Reset/vars/CVP-base.yml
   
  tasks:
    - name: "Gather CVP facts"
      arista.cvp.cv_facts:
      register: CVP_FACTS

    - name: "Build default container topology"
      arista.cvp.cv_container:
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        topology: "{{CONTAINERS_DEFAULT}}"
        mode: merge
      register: CVP_CONTAINERS_RESULT
    - name: "Print debug for containers module"
      debug:
        msg: "{{CVP_CONTAINERS_RESULT}}"
    
    - name: "Apply configlets for default config"
      arista.cvp.cv_device:
        devices: "{{ CVP_DEVICES_DEFAULT }}"
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        state: present
      register: CVP_DEVICES_RESULTS

  # tasks:
  # - name: "Gather CVP facts {{inventory_hostname}}"
  #   arista.cvp.cv_facts:
  #   register: CVP_FACTS
  # - name: "Configure devices on {{inventory_hostname}}"
  #   arista.cvp.cv_device:
  #     devices: "{{CVP_DEVICES_DEFAULT}}"
  #     cvp_facts: "{{CVP_FACTS.ansible_facts}}"
  #     state: present
  #   register: CVP_DEVICES_RESULTS

  