---
- name: Assign configlets to devices (via group_vars/CVP.yml)
  hosts: CloudVision
  connection: local
  gather_facts: no

  vars: 
    path: "{{lookup('env','PWD')}}"
  vars_files: 
     - /home/coder/project/persist/ATD-Lab-Reset/vars/CVP-base.yml
   
  tasks:

    - name: "Build default container topology"
      arista.cvp.cv_container_v3:
        topology: "{{CONTAINERS_DEFAULT}}"

    - name: "Apply configlets for default config"
      arista.cvp.cv_device_v3:
        devices: "{{ CVP_DEVICES_DEFAULT }}"
        cvp_facts: "{{CVP_FACTS.ansible_facts}}"
        state: present
      register: CVP_DEVICES_RESULTS

