---
- name: Upload all configlets (OSPF)
  hosts: CloudVision
  connection: local
  gather_facts: no
  vars:
    path: "{{lookup('env','PWD')}}"
  tasks:
    - name: Push config to CVP
      arista.cvp.cv_configlet_v3:
        configlets: "{{CVP_CONFIGLETS_OSPF}}"
        state: present 